import {EtroMateriaTier} from './gearset.types';

// https://etro.gg/api/materia
export const etroMateriaListMock = [
    {
        id: 16,
        param: 44,
        paramName: 'Determination',
        tier1: {
            id: 5674,
            name: 'Savage Might Materia I',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20221,
            iconPath: '/i/020000/020221.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5675,
            name: 'Savage Might Materia II',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20222,
            iconPath: '/i/020000/020222.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5676,
            name: 'Savage Might Materia III',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20223,
            iconPath: '/i/020000/020223.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5677,
            name: 'Savage Might Materia IV',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20224,
            iconPath: '/i/020000/020224.png',
            itemLevel: 70,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5678,
            name: 'Savage Might Materia V',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20258,
            iconPath: '/i/020000/020258.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 6,
        tier6: {
            id: 18020,
            name: 'Savage Might Materia VI',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20267,
            iconPath: '/i/020000/020267.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 16,
        tier7: {
            id: 25189,
            name: 'Savage Might Materia VII',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20274,
            iconPath: '/i/020000/020274.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 8,
        tier8: {
            id: 26730,
            name: 'Savage Might Materia VIII',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20279,
            iconPath: '/i/020000/020279.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 24,
        tier9: {
            id: 33920,
            name: 'Savage Might Materia IX',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20284,
            iconPath: '/i/020000/020284.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 12,
        tier10: {
            id: 33933,
            name: 'Savage Might Materia X',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20289,
            iconPath: '/i/020000/020289.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 36
    },
    {
        id: 18,
        param: 72,
        paramName: 'Gathering',
        tier1: {
            id: 5684,
            name: "Gatherer's Guerdon Materia I",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20209,
            iconPath: '/i/020000/020209.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 3,
        tier2: {
            id: 5685,
            name: "Gatherer's Guerdon Materia II",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20210,
            iconPath: '/i/020000/020210.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 4,
        tier3: {
            id: 5686,
            name: "Gatherer's Guerdon Materia III",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20211,
            iconPath: '/i/020000/020211.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 5,
        tier4: {
            id: 5687,
            name: "Gatherer's Guerdon Materia IV",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20212,
            iconPath: '/i/020000/020212.png',
            itemLevel: 55,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 6,
        tier5: {
            id: 5688,
            name: "Gatherer's Guerdon Materia V",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20255,
            iconPath: '/i/020000/020255.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 10,
        tier6: {
            id: 18022,
            name: "Gatherer's Guerdon Materia VI",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20266,
            iconPath: '/i/020000/020266.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 15,
        tier7: {
            id: 25191,
            name: "Gatherer's Guerdon Materia VII",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20272,
            iconPath: '/i/020000/020272.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 12,
        tier8: {
            id: 26732,
            name: "Gatherer's Guerdon Materia VIII",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20277,
            iconPath: '/i/020000/020277.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 20,
        tier9: {
            id: 33922,
            name: "Gatherer's Guerdon Materia IX",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20283,
            iconPath: '/i/020000/020283.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 14,
        tier10: {
            id: 33935,
            name: "Gatherer's Guerdon Materia X",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20288,
            iconPath: '/i/020000/020288.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 25
    },
    {
        id: 19,
        param: 73,
        paramName: 'Perception',
        tier1: {
            id: 5689,
            name: "Gatherer's Guile Materia I",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20209,
            iconPath: '/i/020000/020209.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 3,
        tier2: {
            id: 5690,
            name: "Gatherer's Guile Materia II",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20210,
            iconPath: '/i/020000/020210.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 4,
        tier3: {
            id: 5691,
            name: "Gatherer's Guile Materia III",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20211,
            iconPath: '/i/020000/020211.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 5,
        tier4: {
            id: 5692,
            name: "Gatherer's Guile Materia IV",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20212,
            iconPath: '/i/020000/020212.png',
            itemLevel: 55,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 6,
        tier5: {
            id: 5693,
            name: "Gatherer's Guile Materia V",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20255,
            iconPath: '/i/020000/020255.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 10,
        tier6: {
            id: 18023,
            name: "Gatherer's Guile Materia VI",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20266,
            iconPath: '/i/020000/020266.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 15,
        tier7: {
            id: 25192,
            name: "Gatherer's Guile Materia VII",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20272,
            iconPath: '/i/020000/020272.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 12,
        tier8: {
            id: 26733,
            name: "Gatherer's Guile Materia VIII",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20277,
            iconPath: '/i/020000/020277.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 20,
        tier9: {
            id: 33923,
            name: "Gatherer's Guile Materia IX",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20283,
            iconPath: '/i/020000/020283.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 14,
        tier10: {
            id: 33936,
            name: "Gatherer's Guile Materia X",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20288,
            iconPath: '/i/020000/020288.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 25
    },
    {
        id: 7,
        param: 6,
        paramName: 'Piety',
        tier1: {
            id: 5629,
            name: 'Piety Materia I',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20213,
            iconPath: '/i/020000/020213.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5630,
            name: 'Piety Materia II',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20214,
            iconPath: '/i/020000/020214.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5631,
            name: 'Piety Materia III',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20215,
            iconPath: '/i/020000/020215.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5632,
            name: 'Piety Materia IV',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20216,
            iconPath: '/i/020000/020216.png',
            itemLevel: 70,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5633,
            name: 'Piety Materia V',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20256,
            iconPath: '/i/020000/020256.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 6,
        tier6: {
            id: 18011,
            name: 'Piety Materia VI',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20262,
            iconPath: '/i/020000/020262.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 16,
        tier7: {
            id: 25186,
            name: 'Piety Materia VII',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20273,
            iconPath: '/i/020000/020273.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 8,
        tier8: {
            id: 26727,
            name: 'Piety Materia VIII',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20278,
            iconPath: '/i/020000/020278.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 24,
        tier9: {
            id: 33917,
            name: 'Piety Materia IX',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20281,
            iconPath: '/i/020000/020281.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 12,
        tier10: {
            id: 33930,
            name: 'Piety Materia X',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20286,
            iconPath: '/i/020000/020286.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 36
    },
    {
        id: 20,
        param: 10,
        paramName: 'GP',
        tier1: {
            id: 5694,
            name: "Gatherer's Grasp Materia I",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20209,
            iconPath: '/i/020000/020209.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5695,
            name: "Gatherer's Grasp Materia II",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20210,
            iconPath: '/i/020000/020210.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5696,
            name: "Gatherer's Grasp Materia III",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20211,
            iconPath: '/i/020000/020211.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5697,
            name: "Gatherer's Grasp Materia IV",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20212,
            iconPath: '/i/020000/020212.png',
            itemLevel: 55,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5698,
            name: "Gatherer's Grasp Materia V",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20255,
            iconPath: '/i/020000/020255.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 6,
        tier6: {
            id: 18024,
            name: "Gatherer's Grasp Materia VI",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20266,
            iconPath: '/i/020000/020266.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 8,
        tier7: {
            id: 25193,
            name: "Gatherer's Grasp Materia VII",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20272,
            iconPath: '/i/020000/020272.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 7,
        tier8: {
            id: 26734,
            name: "Gatherer's Grasp Materia VIII",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20277,
            iconPath: '/i/020000/020277.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 9,
        tier9: {
            id: 33924,
            name: "Gatherer's Grasp Materia IX",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20283,
            iconPath: '/i/020000/020283.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 8,
        tier10: {
            id: 33937,
            name: "Gatherer's Grasp Materia X",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20288,
            iconPath: '/i/020000/020288.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 10
    },
    {
        id: 25,
        param: 46,
        paramName: 'Spell Speed',
        tier1: {
            id: 5719,
            name: 'Quicktongue Materia I',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20225,
            iconPath: '/i/020000/020225.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5720,
            name: 'Quicktongue Materia II',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20226,
            iconPath: '/i/020000/020226.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5721,
            name: 'Quicktongue Materia III',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20227,
            iconPath: '/i/020000/020227.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5722,
            name: 'Quicktongue Materia IV',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20228,
            iconPath: '/i/020000/020228.png',
            itemLevel: 70,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5723,
            name: 'Quicktongue Materia V',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20259,
            iconPath: '/i/020000/020259.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 6,
        tier6: {
            id: 18029,
            name: 'Quicktongue Materia VI',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20265,
            iconPath: '/i/020000/020265.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 16,
        tier7: {
            id: 25198,
            name: 'Quicktongue Materia VII',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20275,
            iconPath: '/i/020000/020275.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 8,
        tier8: {
            id: 26739,
            name: 'Quicktongue Materia VIII',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20280,
            iconPath: '/i/020000/020280.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 24,
        tier9: {
            id: 33929,
            name: 'Quicktongue Materia IX',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20282,
            iconPath: '/i/020000/020282.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 12,
        tier10: {
            id: 33942,
            name: 'Quicktongue Materia X',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20287,
            iconPath: '/i/020000/020287.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 36
    },
    {
        id: 23,
        param: 71,
        paramName: 'Control',
        tier1: {
            id: 5709,
            name: "Craftsman's Command Materia I",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20201,
            iconPath: '/i/020000/020201.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5710,
            name: "Craftsman's Command Materia II",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20202,
            iconPath: '/i/020000/020202.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5711,
            name: "Craftsman's Command Materia III",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20203,
            iconPath: '/i/020000/020203.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5712,
            name: "Craftsman's Command Materia IV",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20204,
            iconPath: '/i/020000/020204.png',
            itemLevel: 55,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5713,
            name: "Craftsman's Command Materia V",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20253,
            iconPath: '/i/020000/020253.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 7,
        tier6: {
            id: 18027,
            name: "Craftsman's Command Materia VI",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20270,
            iconPath: '/i/020000/020270.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 10,
        tier7: {
            id: 25196,
            name: "Craftsman's Command Materia VII",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20271,
            iconPath: '/i/020000/020271.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 9,
        tier8: {
            id: 26737,
            name: "Craftsman's Command Materia VIII",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20276,
            iconPath: '/i/020000/020276.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 13,
        tier9: {
            id: 33927,
            name: "Craftsman's Command Materia IX",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20285,
            iconPath: '/i/020000/020285.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 12,
        tier10: {
            id: 33940,
            name: "Craftsman's Command Materia X",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20290,
            iconPath: '/i/020000/020290.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 18
    },
    {
        id: 21,
        param: 70,
        paramName: 'Craftsmanship',
        tier1: {
            id: 5699,
            name: "Craftsman's Competence Materia I",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20201,
            iconPath: '/i/020000/020201.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 3,
        tier2: {
            id: 5700,
            name: "Craftsman's Competence Materia II",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20202,
            iconPath: '/i/020000/020202.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 4,
        tier3: {
            id: 5701,
            name: "Craftsman's Competence Materia III",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20203,
            iconPath: '/i/020000/020203.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 5,
        tier4: {
            id: 5702,
            name: "Craftsman's Competence Materia IV",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20204,
            iconPath: '/i/020000/020204.png',
            itemLevel: 55,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 6,
        tier5: {
            id: 5703,
            name: "Craftsman's Competence Materia V",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20253,
            iconPath: '/i/020000/020253.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 11,
        tier6: {
            id: 18025,
            name: "Craftsman's Competence Materia VI",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20270,
            iconPath: '/i/020000/020270.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 16,
        tier7: {
            id: 25194,
            name: "Craftsman's Competence Materia VII",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20271,
            iconPath: '/i/020000/020271.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 14,
        tier8: {
            id: 26735,
            name: "Craftsman's Competence Materia VIII",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20276,
            iconPath: '/i/020000/020276.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 21,
        tier9: {
            id: 33925,
            name: "Craftsman's Competence Materia IX",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20285,
            iconPath: '/i/020000/020285.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 18,
        tier10: {
            id: 33938,
            name: "Craftsman's Competence Materia X",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20290,
            iconPath: '/i/020000/020290.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 27
    },
    {
        id: 14,
        param: 22,
        paramName: 'Direct Hit Rate',
        tier1: {
            id: 5664,
            name: "Heavens' Eye Materia I",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20221,
            iconPath: '/i/020000/020221.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5665,
            name: "Heavens' Eye Materia II",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20222,
            iconPath: '/i/020000/020222.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5666,
            name: "Heavens' Eye Materia III",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20223,
            iconPath: '/i/020000/020223.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5667,
            name: "Heavens' Eye Materia IV",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20224,
            iconPath: '/i/020000/020224.png',
            itemLevel: 70,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5668,
            name: "Heavens' Eye Materia V",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20258,
            iconPath: '/i/020000/020258.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 6,
        tier6: {
            id: 18018,
            name: "Heavens' Eye Materia VI",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20267,
            iconPath: '/i/020000/020267.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 16,
        tier7: {
            id: 25187,
            name: "Heavens' Eye Materia VII",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20274,
            iconPath: '/i/020000/020274.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 8,
        tier8: {
            id: 26728,
            name: "Heavens' Eye Materia VIII",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20279,
            iconPath: '/i/020000/020279.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 24,
        tier9: {
            id: 33918,
            name: "Heavens' Eye Materia IX",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20284,
            iconPath: '/i/020000/020284.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 12,
        tier10: {
            id: 33931,
            name: "Heavens' Eye Materia X",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20289,
            iconPath: '/i/020000/020289.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 36
    },
    {
        id: 24,
        param: 45,
        paramName: 'Skill Speed',
        tier1: {
            id: 5714,
            name: 'Quickarm Materia I',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20225,
            iconPath: '/i/020000/020225.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5715,
            name: 'Quickarm Materia II',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20226,
            iconPath: '/i/020000/020226.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5716,
            name: 'Quickarm Materia III',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20227,
            iconPath: '/i/020000/020227.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5717,
            name: 'Quickarm Materia IV',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20228,
            iconPath: '/i/020000/020228.png',
            itemLevel: 70,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5718,
            name: 'Quickarm Materia V',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20259,
            iconPath: '/i/020000/020259.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 6,
        tier6: {
            id: 18028,
            name: 'Quickarm Materia VI',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20265,
            iconPath: '/i/020000/020265.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 16,
        tier7: {
            id: 25197,
            name: 'Quickarm Materia VII',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20275,
            iconPath: '/i/020000/020275.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 8,
        tier8: {
            id: 26738,
            name: 'Quickarm Materia VIII',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20280,
            iconPath: '/i/020000/020280.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 24,
        tier9: {
            id: 33928,
            name: 'Quickarm Materia IX',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20282,
            iconPath: '/i/020000/020282.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 12,
        tier10: {
            id: 33941,
            name: 'Quickarm Materia X',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20287,
            iconPath: '/i/020000/020287.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 36
    },
    {
        id: 22,
        param: 11,
        paramName: 'CP',
        tier1: {
            id: 5704,
            name: "Craftsman's Cunning Materia I",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20201,
            iconPath: '/i/020000/020201.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5705,
            name: "Craftsman's Cunning Materia II",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20202,
            iconPath: '/i/020000/020202.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5706,
            name: "Craftsman's Cunning Materia III",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20203,
            iconPath: '/i/020000/020203.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5707,
            name: "Craftsman's Cunning Materia IV",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20204,
            iconPath: '/i/020000/020204.png',
            itemLevel: 55,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5708,
            name: "Craftsman's Cunning Materia V",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20253,
            iconPath: '/i/020000/020253.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 6,
        tier6: {
            id: 18026,
            name: "Craftsman's Cunning Materia VI",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20270,
            iconPath: '/i/020000/020270.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 8,
        tier7: {
            id: 25195,
            name: "Craftsman's Cunning Materia VII",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20271,
            iconPath: '/i/020000/020271.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 7,
        tier8: {
            id: 26736,
            name: "Craftsman's Cunning Materia VIII",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20276,
            iconPath: '/i/020000/020276.png',
            itemLevel: 430,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 9,
        tier9: {
            id: 33926,
            name: "Craftsman's Cunning Materia IX",
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20285,
            iconPath: '/i/020000/020285.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 8,
        tier10: {
            id: 33939,
            name: "Craftsman's Cunning Materia X",
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20290,
            iconPath: '/i/020000/020290.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 10
    },
    {
        id: 15,
        param: 27,
        paramName: 'Critical Hit',
        tier1: {
            id: 5669,
            name: 'Savage Aim Materia I',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20221,
            iconPath: '/i/020000/020221.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5670,
            name: 'Savage Aim Materia II',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20222,
            iconPath: '/i/020000/020222.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5671,
            name: 'Savage Aim Materia III',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20223,
            iconPath: '/i/020000/020223.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5672,
            name: 'Savage Aim Materia IV',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20224,
            iconPath: '/i/020000/020224.png',
            itemLevel: 70,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5673,
            name: 'Savage Aim Materia V',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20258,
            iconPath: '/i/020000/020258.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 6,
        tier6: {
            id: 18019,
            name: 'Savage Aim Materia VI',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20267,
            iconPath: '/i/020000/020267.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 16,
        tier7: {
            id: 25188,
            name: 'Savage Aim Materia VII',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20274,
            iconPath: '/i/020000/020274.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 8,
        tier8: {
            id: 26729,
            name: 'Savage Aim Materia VIII',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20279,
            iconPath: '/i/020000/020279.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 24,
        tier9: {
            id: 33919,
            name: 'Savage Aim Materia IX',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20284,
            iconPath: '/i/020000/020284.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 12,
        tier10: {
            id: 33932,
            name: 'Savage Aim Materia X',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20289,
            iconPath: '/i/020000/020289.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 36
    },
    {
        id: 17,
        param: 19,
        paramName: 'Tenacity',
        tier1: {
            id: 5679,
            name: 'Battledance Materia I',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20213,
            iconPath: '/i/020000/020213.png',
            itemLevel: 15,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier1Value: 1,
        tier2: {
            id: 5680,
            name: 'Battledance Materia II',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20214,
            iconPath: '/i/020000/020214.png',
            itemLevel: 30,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier2Value: 2,
        tier3: {
            id: 5681,
            name: 'Battledance Materia III',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20215,
            iconPath: '/i/020000/020215.png',
            itemLevel: 45,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier3Value: 3,
        tier4: {
            id: 5682,
            name: 'Battledance Materia IV',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20216,
            iconPath: '/i/020000/020216.png',
            itemLevel: 70,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier4Value: 4,
        tier5: {
            id: 5683,
            name: 'Battledance Materia V',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20256,
            iconPath: '/i/020000/020256.png',
            itemLevel: 160,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier5Value: 6,
        tier6: {
            id: 18021,
            name: 'Battledance Materia VI',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20262,
            iconPath: '/i/020000/020262.png',
            itemLevel: 290,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier6Value: 16,
        tier7: {
            id: 25190,
            name: 'Battledance Materia VII',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20273,
            iconPath: '/i/020000/020273.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier7Value: 8,
        tier8: {
            id: 26731,
            name: 'Battledance Materia VIII',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20278,
            iconPath: '/i/020000/020278.png',
            itemLevel: 420,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier8Value: 24,
        tier9: {
            id: 33921,
            name: 'Battledance Materia IX',
            description: '',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20281,
            iconPath: '/i/020000/020281.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier9Value: 12,
        tier10: {
            id: 33934,
            name: 'Battledance Materia X',
            description:
                'Cannot be melded onto a piece of equipment past the first advanced materia melding slot.',
            advancedMelding: true,
            canBeHq: false,
            iconId: 20286,
            iconPath: '/i/020000/020286.png',
            itemLevel: 560,
            itemUICategory: 58,
            level: 1,
            materiaSlotCount: 0,
            materializeType: 0,
            rarity: 1,
            unique: false,
            untradable: false
        },
        tier10Value: 36
    }
];

// https://etro.gg/api/gearsets/e78a29e3-1dcf-4e53-bbcf-234f33b2c831/
export const etroGearsetMock = {
    id: 'e78a29e3-1dcf-4e53-bbcf-234f33b2c831',
    jobAbbrev: 'WHM',
    jobIconPath: '/jobs/WHM.svg',
    clanName: 'Midlander',
    isOwner: false,
    name: 'Low Piety BiS',
    lastUpdate: '2022-01-10T02:15:49.297760Z',
    minItemLevel: 600,
    maxItemLevel: 605,
    minMateriaTier: 10,
    maxMateriaTier: 10,
    materia: {
        '35215': {
            '1': 33932,
            '2': 33932
        },
        '35217': {
            '1': 33931,
            '2': 33931
        },
        '35218': {
            '1': 33932,
            '2': 33932
        },
        '35219': {
            '1': 33932,
            '2': 33931
        },
        '35228': {
            '1': 33932,
            '2': 33931
        },
        '35233': {
            '1': 33931,
            '2': 33931
        },
        '35253': {
            '1': 33932,
            '2': 33932
        },
        '35290': {
            '1': 33931,
            '2': 33931
        },
        '35291': {
            '1': 33932,
            '2': 33932
        },
        '35294': {
            '1': 33931,
            '2': 33931
        },
        '35303': {
            '1': 33931,
            '2': 33931
        },
        '35308': {
            '1': 33932,
            '2': 33931
        },
        '35313': {
            '1': 33931,
            '2': 33931
        },
        '35243R': {
            '1': 33931,
            '2': 33933
        },
        '35318L': {
            '1': 33931,
            '2': 33931
        }
    },
    totalParams: [
        {
            id: '5',
            name: 'MND',
            value: 2571
        },
        {
            id: '3',
            name: 'VIT',
            value: 2481
        },
        {
            id: '21',
            name: 'DEF',
            value: 1777
        },
        {
            id: '6',
            name: 'PIE',
            value: 592
        },
        {
            id: '22',
            name: 'DH',
            value: 940
        },
        {
            id: '27',
            name: 'CRT',
            value: 2301
        },
        {
            id: '44',
            name: 'DET',
            value: 1830
        },
        {
            id: '46',
            name: 'SPS',
            value: 489
        },
        {
            name: 'GCD',
            units: 's',
            value: 1.98
        },
        {
            name: 'Average Item Level',
            value: 600
        },
        {
            name: 'Critical Hit Multiplier',
            units: '%',
            value: 160
        },
        {
            name: 'Critical Hit Rate',
            units: '%',
            value: 25
        },
        {
            name: 'Defense Mitigation',
            units: '%',
            value: 14
        },
        {
            name: 'Determination Multiplier',
            units: '%',
            value: 110.6
        },
        {
            name: 'Direct Hit Rate',
            units: '%',
            value: 15.6
        },
        {
            name: 'HP',
            value: 53961
        },
        {
            name: 'MND Multiplier',
            units: '%',
            value: 111.9
        },
        {
            name: 'MP per Tick',
            value: 215
        },
        {
            name: 'Spell Speed Multiplier',
            units: '%',
            value: 100.6
        },
        {
            id: 13,
            name: 'Weapon Damage',
            value: 120
        }
    ],
    buffs: null,
    relics: null,
    patch: 6.0,
    job: 24,
    clan: 1,
    weapon: 35253,
    head: 35290,
    body: 35291,
    hands: 35217,
    legs: 35218,
    feet: 35294,
    offHand: null,
    ears: 35303,
    neck: 35233,
    wrists: 35313,
    fingerL: 35318,
    fingerR: 35243,
    food: 545,
    medicine: null
};

// http://localhost:3001/gearset/cc743560-11c4-4fe3-89fd-64534cfa50ca
export const gearsetMock = {
    id: 'bd287613-ca59-45b7-b50d-5465daca9ccc',
    jobAbbrev: 'SGE',
    name: '6.2 NR Mixed',
    lastUpdate: '2022-08-27T00:40:50.920096Z',
    bisLink: undefined,
    food: {
        id: 578,
        name: 'Garlean Pizza',
        iconPath: '/i/024000/hq/024034.png'
    },
    weapon: {
        id: 37759,
        equipment_name: 'Rinascita Pendulums',
        slotName: 'weapon'
    },
    head: {
        id: 37787,
        equipment_name: 'Rinascita Beret of Healing',
        slotName: 'head'
    },
    body: {
        id: 37902,
        equipment_name: 'Purgatory Surcoat of Healing',
        slotName: 'body'
    },
    hands: {
        id: 37789,
        equipment_name: 'Rinascita Gloves of Healing',
        slotName: 'hands'
    },
    legs: {
        id: 37790,
        equipment_name: 'Rinascita Poleyns of Healing',
        slotName: 'legs'
    },
    feet: {
        id: 37905,
        equipment_name: 'Purgatory Boots of Healing',
        slotName: 'feet'
    },
    offHand: {id: 0, equipment_name: '', slotName: 'unknown'},
    ears: {
        id: 37914,
        equipment_name: 'Purgatory Earrings of Healing',
        slotName: 'ears'
    },
    neck: {
        id: 37919,
        equipment_name: 'Purgatory Choker of Healing',
        slotName: 'neck'
    },
    wrists: {
        id: 37810,
        equipment_name: 'Rinascita Bracelet of Healing',
        slotName: 'wrists'
    },
    fingerL: {
        id: 37929,
        equipment_name: 'Purgatory Ring of Healing',
        slotName: 'finger_l'
    },
    fingerR: {
        id: 37815,
        equipment_name: 'Rinascita Ring of Healing',
        slotName: 'finger_r'
    }
};
