export const jobsMock = [
    {
        id: 38,
        abbrev: 'DNC',
        name: 'Dancer',
        iconPath: '/jobs/DNC.svg',
        DEX: 115,
        INT: 85,
        MND: 80,
        VIT: 100,
        PIE: 100,
        STR: 90,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 23,
        abbrev: 'BRD',
        name: 'Bard',
        iconPath: '/jobs/BRD.svg',
        DEX: 115,
        INT: 85,
        MND: 80,
        VIT: 100,
        PIE: 100,
        STR: 90,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 15,
        abbrev: 'CUL',
        name: 'Culinarian',
        iconPath: '/jobs/CUL.svg',
        DEX: 90,
        INT: 90,
        MND: 105,
        VIT: 90,
        PIE: 100,
        STR: 90,
        HP: 100,
        isCrafting: true,
        isGathering: false
    },
    {
        id: 32,
        abbrev: 'DRK',
        name: 'Dark Knight',
        iconPath: '/jobs/DRK.svg',
        DEX: 95,
        INT: 60,
        MND: 40,
        VIT: 110,
        PIE: 100,
        STR: 105,
        HP: 140,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 28,
        abbrev: 'SCH',
        name: 'Scholar',
        iconPath: '/jobs/SCH.svg',
        DEX: 100,
        INT: 105,
        MND: 115,
        VIT: 100,
        PIE: 100,
        STR: 90,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 19,
        abbrev: 'PLD',
        name: 'Paladin',
        iconPath: '/jobs/PLD.svg',
        DEX: 95,
        INT: 60,
        MND: 100,
        VIT: 110,
        PIE: 100,
        STR: 100,
        HP: 140,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 25,
        abbrev: 'BLM',
        name: 'Black Mage',
        iconPath: '/jobs/BLM.svg',
        DEX: 100,
        INT: 115,
        MND: 75,
        VIT: 100,
        PIE: 100,
        STR: 45,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 31,
        abbrev: 'MCH',
        name: 'Machinist',
        iconPath: '/jobs/MCH.svg',
        DEX: 115,
        INT: 80,
        MND: 85,
        VIT: 100,
        PIE: 100,
        STR: 85,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 14,
        abbrev: 'ALC',
        name: 'Alchemist',
        iconPath: '/jobs/ALC.svg',
        DEX: 90,
        INT: 105,
        MND: 90,
        VIT: 90,
        PIE: 100,
        STR: 90,
        HP: 100,
        isCrafting: true,
        isGathering: false
    },
    {
        id: 22,
        abbrev: 'DRG',
        name: 'Dragoon',
        iconPath: '/jobs/DRG.svg',
        DEX: 100,
        INT: 45,
        MND: 65,
        VIT: 105,
        PIE: 100,
        STR: 115,
        HP: 115,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 40,
        abbrev: 'SGE',
        name: 'Sage',
        iconPath: '/jobs/SGE.svg',
        DEX: 100,
        INT: 115,
        MND: 115,
        VIT: 100,
        PIE: 100,
        STR: 60,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 37,
        abbrev: 'GNB',
        name: 'Gunbreaker',
        iconPath: '/jobs/GNB.svg',
        DEX: 95,
        INT: 60,
        MND: 100,
        VIT: 110,
        PIE: 100,
        STR: 100,
        HP: 140,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 13,
        abbrev: 'WVR',
        name: 'Weaver',
        iconPath: '/jobs/WVR.svg',
        DEX: 105,
        INT: 90,
        MND: 100,
        VIT: 90,
        PIE: 100,
        STR: 90,
        HP: 100,
        isCrafting: true,
        isGathering: false
    },
    {
        id: 9,
        abbrev: 'BSM',
        name: 'Blacksmith',
        iconPath: '/jobs/BSM.svg',
        DEX: 90,
        INT: 90,
        MND: 100,
        VIT: 90,
        PIE: 100,
        STR: 105,
        HP: 100,
        isCrafting: true,
        isGathering: false
    },
    {
        id: 17,
        abbrev: 'BTN',
        name: 'Botanist',
        iconPath: '/jobs/BTN.svg',
        DEX: 100,
        INT: 100,
        MND: 90,
        VIT: 90,
        PIE: 100,
        STR: 90,
        HP: 100,
        isCrafting: false,
        isGathering: true
    },
    {
        id: 27,
        abbrev: 'SMN',
        name: 'Summoner',
        iconPath: '/jobs/SMN.svg',
        DEX: 100,
        INT: 115,
        MND: 80,
        VIT: 100,
        PIE: 100,
        STR: 90,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 10,
        abbrev: 'ARM',
        name: 'Armorer',
        iconPath: '/jobs/ARM.svg',
        DEX: 90,
        INT: 90,
        MND: 90,
        VIT: 105,
        PIE: 100,
        STR: 100,
        HP: 100,
        isCrafting: true,
        isGathering: false
    },
    {
        id: 18,
        abbrev: 'FSH',
        name: 'Fisher',
        iconPath: '/jobs/FSH.svg',
        DEX: 100,
        INT: 100,
        MND: 100,
        VIT: 100,
        PIE: 100,
        STR: 100,
        HP: 100,
        isCrafting: false,
        isGathering: true
    },
    {
        id: 21,
        abbrev: 'WAR',
        name: 'Warrior',
        iconPath: '/jobs/WAR.svg',
        DEX: 95,
        INT: 40,
        MND: 55,
        VIT: 110,
        PIE: 100,
        STR: 105,
        HP: 145,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 11,
        abbrev: 'GSM',
        name: 'Goldsmith',
        iconPath: '/jobs/GSM.svg',
        DEX: 105,
        INT: 100,
        MND: 90,
        VIT: 90,
        PIE: 100,
        STR: 90,
        HP: 100,
        isCrafting: true,
        isGathering: false
    },
    {
        id: 34,
        abbrev: 'SAM',
        name: 'Samurai',
        iconPath: '/jobs/SAM.svg',
        DEX: 108,
        INT: 60,
        MND: 50,
        VIT: 100,
        PIE: 100,
        STR: 112,
        HP: 109,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 30,
        abbrev: 'NIN',
        name: 'Ninja',
        iconPath: '/jobs/NIN.svg',
        DEX: 110,
        INT: 65,
        MND: 75,
        VIT: 100,
        PIE: 100,
        STR: 85,
        HP: 108,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 39,
        abbrev: 'RPR',
        name: 'Reaper',
        iconPath: '/jobs/RPR.svg',
        DEX: 100,
        INT: 80,
        MND: 40,
        VIT: 105,
        PIE: 100,
        STR: 115,
        HP: 115,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 16,
        abbrev: 'MIN',
        name: 'Miner',
        iconPath: '/jobs/MIN.svg',
        DEX: 90,
        INT: 90,
        MND: 100,
        VIT: 90,
        PIE: 100,
        STR: 100,
        HP: 100,
        isCrafting: false,
        isGathering: true
    },
    {
        id: 8,
        abbrev: 'CRP',
        name: 'Carpenter',
        iconPath: '/jobs/CRP.svg',
        DEX: 100,
        INT: 90,
        MND: 90,
        VIT: 105,
        PIE: 100,
        STR: 90,
        HP: 100,
        isCrafting: true,
        isGathering: false
    },
    {
        id: 12,
        abbrev: 'LTW',
        name: 'Leatherworker',
        iconPath: '/jobs/LTW.svg',
        DEX: 90,
        INT: 100,
        MND: 90,
        VIT: 105,
        PIE: 100,
        STR: 90,
        HP: 100,
        isCrafting: true,
        isGathering: false
    },
    {
        id: 20,
        abbrev: 'MNK',
        name: 'Monk',
        iconPath: '/jobs/MNK.svg',
        DEX: 105,
        INT: 50,
        MND: 90,
        VIT: 100,
        PIE: 100,
        STR: 110,
        HP: 110,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 24,
        abbrev: 'WHM',
        name: 'White Mage',
        iconPath: '/jobs/WHM.svg',
        DEX: 105,
        INT: 105,
        MND: 115,
        VIT: 100,
        PIE: 100,
        STR: 55,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 33,
        abbrev: 'AST',
        name: 'Astrologian',
        iconPath: '/jobs/AST.svg',
        DEX: 100,
        INT: 105,
        MND: 115,
        VIT: 100,
        PIE: 100,
        STR: 50,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 36,
        abbrev: 'BLU',
        name: 'Blue Mage',
        iconPath: '/jobs/BLU.svg',
        DEX: 110,
        INT: 115,
        MND: 105,
        VIT: 100,
        PIE: 100,
        STR: 70,
        HP: 105,
        isCrafting: false,
        isGathering: false
    },
    {
        id: 35,
        abbrev: 'RDM',
        name: 'Red Mage',
        iconPath: '/jobs/RDM.svg',
        DEX: 105,
        INT: 115,
        MND: 110,
        VIT: 100,
        PIE: 100,
        STR: 55,
        HP: 105,
        isCrafting: false,
        isGathering: false
    }
];
